#pragma once

#define FULL_WIDTH 1024
#define FULL_HEIGHT 768
#define FULL_LENGTH FULL_WIDTH * FULL_HEIGHT
#define SEARCH_WIDTH 36
#define SEARCH_HEIGHT 49
#define SEARCH_LENGTH SEARCH_WIDTH * SEARCH_HEIGHT