#pragma once

#define LARGE_WIDTH 1024
#define LARGE_HEIGHT 768
#define LARGE_LENGTH LARGE_WIDTH * LARGE_HEIGHT
#define SEARCH_WIDTH 36
#define SEARCH_HEIGHT 49
#define SEARCH_LENGTH SEARCH_WIDTH * SEARCH_HEIGHT